### ISSUE TITLE
Please add terrain slope detection!

### ISSUE THREAD

**Issue by Thundros** [jonlo/threejs-aabb-collision-engine-TestScene#1]
@jonlo : Hi, first off I'd like to say GREAT JOB! Keep up the awesome work!

Second, I'd like to ask if you could please add Terrain slope detection based on a given X rotation angle?

Thank You!

**Comment by Thundros** [comment]
@jonlo : Hello?

**Comment by jonlo** [comment]
Hey, i'm thanks for the nice comment, for now im just trying to develop a simple aabb collision system, not thinking about terrains or complex meshes, sorry.
